const data = {
  products: [
    {
      name: "Polo Shirt",
      price: 5999,
      image: "https://i.postimg.cc/1tj3zLK2/black-polo-04.jpg",
      colors: ["#ff0000", "#00ff00", "#0000ff"],
      company: "Polo",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "polo",
      shipping: true,
      countInStock: 5,
      numReviews: 10,
      rating: 4.5,
      slug: "polo-shirt",
    },
    {
      name: "Red T-Shirt",
      price: 9999,
      image: "https://i.postimg.cc/tRzYPM41/red-shirt-04.jpg",
      colors: ["#000", "#ffb900"],
      company: "Adidas",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "shirts",
      countInStock: 5,
      numReviews: 10,
      rating: 4.0,
      slug: "red-t-shirt",
      shipping: true,
    },
    {
      name: "Long shirt",
      price: 2599,
      image: "https://i.postimg.cc/9FLMrwFs/long-shirt-01.jpg",
      colors: ["#000", "#00ff00", "#0000ff"],
      company: "kappa",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "long sleeve",
      countInStock: 5,
      numReviews: 14,
      rating: 4.3,
      slug: "long-shirt",
      shipping: true,
    },
    {
      name: "Grey Polo",
      price: 3999,
      image: "https://i.postimg.cc/Kj5FMw7m/grey-polo-02.jpg",
      colors: ["#0000ff", "#000", "#ffb900", "#ff0000"],
      company: "Polo",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "polo",
      countInStock: 15,
      numReviews: 33,
      rating: 4.0,
      slug: "grey-polo",
      shipping: true,
    },

    {
      name: "Blue polo",
      price: 1459,
      image: " https://i.postimg.cc/C1qxzc6K/blue-polo-03.jpg",
      colors: ["#0000ff", "#000", "#00b900", "#ffb900", "#ff0000"],
      company: "adidas",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "polo",
      countInStock: 6,
      numReviews: 19,
      rating: 4.5,
      slug: "blue-polo",
      shipping: true,
    },
    {
      name: "Black Shirt",
      price: 2399,
      image: " https://i.postimg.cc/nzyMkyQ7/black-shirt-04.jpg",
      colors: ["#0000ff", "#000", "#00b900", "#f0f1f1"],
      company: "puma",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "black",
      countInStock: 5,
      numReviews: 16,
      rating: 5,
      slug: "black-shirt",
      shipping: true,
    },
    {
      name: "Green Shirt",
      price: 2399,
      image: "https://i.postimg.cc/9FRPp2R8/green-shirt-03.jpg ",
      colors: ["#0000ff", "#000", "#00b900", "#f0f1f1", "#ffb900", "#ff0000"],
      company: "nike",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "black",
      countInStock: 5,
      numReviews: 100,
      rating: 4.7,
      slug: "green-shirt",
      shipping: true,
    },
    {
      name: "Long Sleeve green",
      price: 1299,
      image: "https://i.postimg.cc/nzxZdnhv/long-shirt-02.jpg",
      colors: ["#0000ff", "#000", "#00b900", "#f0f1f1"],
      company: "adidas",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "black",
      countInStock: 5,
      numReviews: 80,
      rating: 4.5,
      slug: "long-shirt",
      shipping: true,
    },
    {
      name: "Blue Shirt",
      price: 3399,
      image: "https://i.postimg.cc/k4QzD89S/blue-shirt-02.jpg",
      colors: ["#000", "#00b900", "#f0f1f1", "#0000ff", "#ffb900", "#ff0000"],
      company: "adidas",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "shirt",
      countInStock: 5,
      numReviews: 90,
      rating: 4.5,
      slug: "blue-shirt",
      shipping: true,
    },
    {
      name: "Native wrapper",
      price: 4999,
      image: "https://i.postimg.cc/W3bXnvq9/clothes-01.jpg",
      colors: ["#0000ff", "#000", "#00b900", "#f0f1f1", "#ffb900", "#ff0000"],
      company: "lady nina",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "shirt",
      countInStock: 5,
      numReviews: 10,
      rating: 4.5,
      slug: "african-native",
      shipping: true,
    },
    {
      name: "mayor",
      price: 2399,
      image: "https://i.postimg.cc/3r4Bwcq6/fashion-06.jpg",
      colors: ["#f1f", "#0000ff", "#000", "#00b900", "#f0f1f1"],
      company: "mayor london",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "shirt",
      countInStock: 5,
      numReviews: 110,
      rating: 4.5,
      slug: "mayor",
      shipping: true,
    },
    {
      name: "tutorial native",
      price: 6399,
      image: "https://i.postimg.cc/3xnp1X6m/fashion-02.jpg",
      colors: ["#0000ff", "#000", "#00b900", "#f0f1f1"],
      company: "lady nina",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "shirt",
      countInStock: 5,
      numReviews: 150,
      rating: 4.5,
      slug: "tutorial-native",
      shipping: true,
    },
    {
      name: "cambalan native",
      price: 23999,
      image: "https://i.postimg.cc/bN2Vq5ss/clothes-14.jpg",
      colors: ["#0000ff", "#000", "#00b900", "#f0f1f1"],
      company: "lady nina",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "dress",
      countInStock: 5,
      numReviews: 115,
      rating: 4.0,
      slug: "cambalan-native",
      shipping: true,
    },
    {
      name: "glance native",
      price: 4399,
      image: "https://i.postimg.cc/mk9npp9z/clothes-16.jpg",
      colors: ["#0000ff", "#000", "#00b900", "#f0f1f1"],
      company: "lady nina",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "dress",
      countInStock: 5,
      numReviews: 150,
      rating: 4.5,
      slug: "glance-native",
      shipping: true,
    },
    {
      name: "summer native",
      price: 5499,
      image: "https://i.postimg.cc/mgpSgGt6/fashion-002.jpg",
      colors: ["#0000ff", "#000"],
      company: "lady nina",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "dress",
      countInStock: 5,
      numReviews: 96,
      rating: 4.5,
      slug: "summer-native",
      shipping: true,
    },
    {
      name: "old-school native",
      price: 5699,
      image: "https://i.postimg.cc/zvRmZXsf/clothes-17.jpg",
      colors: ["#0000ff", "#000", "#00b900", "#f0f1f1", "#ffb900", "#ff0000"],
      company: "lady nina",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "dress",
      countInStock: 5,
      numReviews: 10,
      rating: 4.5,
      slug: "oldSchool-native",
      shipping: true,
    },
    {
      name: "coolest native",
      price: 3399,
      image: "https://i.postimg.cc/zXbdjQNq/clothes-18.jpg",
      colors: ["#0000ff", "#000", "#f0f1f1", "#ffb900", "#ff0000"],
      company: "lady nina",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "dress",
      countInStock: 5,
      numReviews: 10,
      rating: 4.5,
      slug: "coolest-native",
      shipping: true,
    },
    {
      name: "fish-style native",
      price: 6599,
      image: "https://i.postimg.cc/6qdfkkpZ/clothes-21.jpg",
      colors: ["#0000ff", "#000", "#f0f1f1", "#ffb900", "#ff0000"],
      company: "lady nina",
      description:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      category: "dress",
      countInStock: 5,
      numReviews: 156,
      rating: 4.5,
      slug: "fish-native",
      shipping: true,
    },
  ],
};

export default data;
